/**
 * This class is generated by jOOQ
 */
package me.taylorkelly.mywarp.dataconnections.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupRecord extends org.jooq.impl.UpdatableRecordImpl<me.taylorkelly.mywarp.dataconnections.jooq.tables.records.GroupRecord> implements org.jooq.Record2<org.jooq.types.UInteger, java.lang.String> {

	private static final long serialVersionUID = -1516598387;

	/**
	 * Setter for <code>mywarp.group.group-id</code>.
	 */
	public void setGroup_id(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mywarp.group.group-id</code>.
	 */
	public org.jooq.types.UInteger getGroup_id() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>mywarp.group.group</code>.
	 */
	public void setGroup(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mywarp.group.group</code>.
	 */
	public java.lang.String getGroup() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<org.jooq.types.UInteger, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<org.jooq.types.UInteger, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return me.taylorkelly.mywarp.dataconnections.jooq.tables.Group.GROUP.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return me.taylorkelly.mywarp.dataconnections.jooq.tables.Group.GROUP.GROUP_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getGroup_id();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getGroup();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupRecord value1(org.jooq.types.UInteger value) {
		setGroup_id(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupRecord value2(java.lang.String value) {
		setGroup(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupRecord values(org.jooq.types.UInteger value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GroupRecord
	 */
	public GroupRecord() {
		super(me.taylorkelly.mywarp.dataconnections.jooq.tables.Group.GROUP);
	}

	/**
	 * Create a detached, initialised GroupRecord
	 */
	public GroupRecord(org.jooq.types.UInteger group_id, java.lang.String group) {
		super(me.taylorkelly.mywarp.dataconnections.jooq.tables.Group.GROUP);

		setValue(0, group_id);
		setValue(1, group);
	}
}
