/**
 * This class is generated by jOOQ
 */
package me.taylorkelly.mywarp.dataconnections.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerRecord extends org.jooq.impl.UpdatableRecordImpl<me.taylorkelly.mywarp.dataconnections.jooq.tables.records.PlayerRecord> implements org.jooq.Record2<org.jooq.types.UInteger, java.util.UUID> {

	private static final long serialVersionUID = -56549801;

	/**
	 * Setter for <code>mywarp.player.player-id</code>.
	 */
	public void setPlayer_id(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mywarp.player.player-id</code>.
	 */
	public org.jooq.types.UInteger getPlayer_id() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>mywarp.player.player</code>.
	 */
	public void setPlayer(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mywarp.player.player</code>.
	 */
	public java.util.UUID getPlayer() {
		return (java.util.UUID) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<org.jooq.types.UInteger, java.util.UUID> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<org.jooq.types.UInteger, java.util.UUID> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return me.taylorkelly.mywarp.dataconnections.jooq.tables.Player.PLAYER.PLAYER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return me.taylorkelly.mywarp.dataconnections.jooq.tables.Player.PLAYER.PLAYER_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getPlayer_id();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getPlayer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value1(org.jooq.types.UInteger value) {
		setPlayer_id(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value2(java.util.UUID value) {
		setPlayer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord values(org.jooq.types.UInteger value1, java.util.UUID value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlayerRecord
	 */
	public PlayerRecord() {
		super(me.taylorkelly.mywarp.dataconnections.jooq.tables.Player.PLAYER);
	}

	/**
	 * Create a detached, initialised PlayerRecord
	 */
	public PlayerRecord(org.jooq.types.UInteger player_id, java.util.UUID player) {
		super(me.taylorkelly.mywarp.dataconnections.jooq.tables.Player.PLAYER);

		setValue(0, player_id);
		setValue(1, player);
	}
}
