/**
 * This class is generated by jOOQ
 */
package me.taylorkelly.mywarp.dataconnections.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = { "http://www.jooq.org", "3.3.1" }, comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Warp2player extends
        org.jooq.impl.TableImpl<me.taylorkelly.mywarp.dataconnections.jooq.tables.records.Warp2playerRecord> {

    private static final long serialVersionUID = -229751559;

    /**
     * The singleton instance of <code>mywarp.warp2player</code>
     */
    public static final me.taylorkelly.mywarp.dataconnections.jooq.tables.Warp2player WARP2PLAYER = new me.taylorkelly.mywarp.dataconnections.jooq.tables.Warp2player();

    /**
     * The class holding records for this type
     */
    @Override
    public java.lang.Class<me.taylorkelly.mywarp.dataconnections.jooq.tables.records.Warp2playerRecord> getRecordType() {
        return me.taylorkelly.mywarp.dataconnections.jooq.tables.records.Warp2playerRecord.class;
    }

    /**
     * The column <code>mywarp.warp2player.player-id</code>.
     */
    public final org.jooq.TableField<me.taylorkelly.mywarp.dataconnections.jooq.tables.records.Warp2playerRecord, org.jooq.types.UInteger> PLAYER_ID = createField(
            "player-id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>mywarp.warp2player.warp-id</code>.
     */
    public final org.jooq.TableField<me.taylorkelly.mywarp.dataconnections.jooq.tables.records.Warp2playerRecord, org.jooq.types.UInteger> WARP_ID = createField(
            "warp-id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>mywarp.warp2player</code> table reference
     */
    public Warp2player() {
        this("warp2player", null);
    }

    /**
     * Create an aliased <code>mywarp.warp2player</code> table reference
     */
    public Warp2player(java.lang.String alias) {
        this(alias, me.taylorkelly.mywarp.dataconnections.jooq.tables.Warp2player.WARP2PLAYER);
    }

    private Warp2player(
            java.lang.String alias,
            org.jooq.Table<me.taylorkelly.mywarp.dataconnections.jooq.tables.records.Warp2playerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Warp2player(
            java.lang.String alias,
            org.jooq.Table<me.taylorkelly.mywarp.dataconnections.jooq.tables.records.Warp2playerRecord> aliased,
            org.jooq.Field<?>[] parameters) {
        super(alias, me.taylorkelly.mywarp.dataconnections.jooq.Mywarp.MYWARP, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.UniqueKey<me.taylorkelly.mywarp.dataconnections.jooq.tables.records.Warp2playerRecord> getPrimaryKey() {
        return me.taylorkelly.mywarp.dataconnections.jooq.Keys.KEY_WARP2PLAYER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.util.List<org.jooq.UniqueKey<me.taylorkelly.mywarp.dataconnections.jooq.tables.records.Warp2playerRecord>> getKeys() {
        return java.util.Arrays
                .<org.jooq.UniqueKey<me.taylorkelly.mywarp.dataconnections.jooq.tables.records.Warp2playerRecord>> asList(me.taylorkelly.mywarp.dataconnections.jooq.Keys.KEY_WARP2PLAYER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.util.List<org.jooq.ForeignKey<me.taylorkelly.mywarp.dataconnections.jooq.tables.records.Warp2playerRecord, ?>> getReferences() {
        return java.util.Arrays
                .<org.jooq.ForeignKey<me.taylorkelly.mywarp.dataconnections.jooq.tables.records.Warp2playerRecord, ?>> asList(
                        me.taylorkelly.mywarp.dataconnections.jooq.Keys.FK_TABLE1_PLAYER1,
                        me.taylorkelly.mywarp.dataconnections.jooq.Keys.FK_TABLE1_WARP1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public me.taylorkelly.mywarp.dataconnections.jooq.tables.Warp2player as(java.lang.String alias) {
        return new me.taylorkelly.mywarp.dataconnections.jooq.tables.Warp2player(alias, this);
    }

    /**
     * Rename this table
     */
    public me.taylorkelly.mywarp.dataconnections.jooq.tables.Warp2player rename(java.lang.String name) {
        return new me.taylorkelly.mywarp.dataconnections.jooq.tables.Warp2player(name, null);
    }
}
