/**
 * This class is generated by jOOQ
 */
package me.taylorkelly.mywarp.dataconnections.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mywarp extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -534822751;

	/**
	 * The singleton instance of <code>mywarp</code>
	 */
	public static final Mywarp MYWARP = new Mywarp();

	/**
	 * No further instances allowed
	 */
	private Mywarp() {
		super("mywarp");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			me.taylorkelly.mywarp.dataconnections.jooq.tables.Group.GROUP,
			me.taylorkelly.mywarp.dataconnections.jooq.tables.Player.PLAYER,
			me.taylorkelly.mywarp.dataconnections.jooq.tables.Warp.WARP,
			me.taylorkelly.mywarp.dataconnections.jooq.tables.Warp2group.WARP2GROUP,
			me.taylorkelly.mywarp.dataconnections.jooq.tables.Warp2player.WARP2PLAYER,
			me.taylorkelly.mywarp.dataconnections.jooq.tables.World.WORLD);
	}
}
