settings:
  controlWorldAccess: false
  teleportHorses: true
  showTeleportEffect: true
  informPlayersOnInvitation: true
storage:
  url: # path is set programatically to a h2 database file in MyWarp's plugin folder
  schema: 'mywarp'
  user: 'mywarp'
  password: 'mywarp'
localization:
  defaultLocale: en_US
  perPlayer: true
teleportSafety:
  enabled: true
  searchRadius: 5
warpSigns:
  enabled: true
  identifiers:
  - MyWarp
  - Warp
limits:
  enabled: true
  defaultLimit:
    totalLimit: 15
    publicLimit: 5
    privateLimit: 10
  configuredLimits: []
timers:
  enabled: false
  warpCooldown:
    notifyOnFinish: false
  warpWarmup:
    abortOnDamage: false
    abortOnMove: false
    notifyOnStart: true
  defaultTimer:
    warpCooldown: 15
    warpWarmup: 15
  configuredTimers: []
economy:
  enabled: false
  informAfterTransaction: true
  defaultFee:
    assets: 0
    create: 25
    createPrivate: 25
    delete: 25
    give: 25
    help: 0
    info: 0
    invite: 25
    list: 0
    point: 25
    private: 25
    public: 25
    uninvite: 25
    update: 25
    warpPlayer: 25
    warpSignCreate: 25
    warpSignUse: 25
    warpTo: 25
    welcome: 25
  configuredFees: []
dynmap:
  enabled: false
  layer:
    displayName: 'MyWarp'
    hiddenByDefault: false
    priority: 10
  marker:
    iconID: 'mywarp_warp-32'
    minZoom: 0
    showLabel: false
    minZoom:
